# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appurl', '0003_auto_20160617_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
