# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appurl', '0006_viewcount_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='session',
        ),
    ]
