# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appurl', '0007_remove_viewcount_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewcount',
            name='view',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
