# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appurl', '0008_auto_20160619_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
